### ISSUE TITLE
ERROR: node-sass not found.

### ISSUE THREAD

**Issue by jamlen** [keystonejs/generator-keystone#83]
So I've just used the generator to build a new site and selected `sass` for stylesheets. It said everything was ready to run, but it errors with:

```
> node keystone.js

ERROR: node-sass not found.

Please install the node-sass-middleware from npm to use the `sass` option.
You can do this by running "npm install node-sass-middleware --save".
```

If I install it as it says it works fine. 

I also tried to just install `node-sass` but that still fails with the same message. (I was looking at https://github.com/keystonejs/keystone/issues/183#issuecomment-46119283)

I probably wont have time to do a PR for this, so thought I'd just raise it!

**Comment by pkosenko** [comment]
I have this same issue with Keystone 0.3.5

Projects that include the SASS option are entirely broken.  You might want to inform the node-sass developers.

https://peterkosenko.wordpress.com/2015/04/24/keystone-js-is-broken-with-sass-option/

**Comment by gabrielseco** [comment]
I see your post and if you use "npm install node-sass-middleware -save"

You have to use --save

I made an example in my computer and all is working well

**Comment by JedWatson** [comment]
I fixed an issue in the latest version of the generator, and Keystone that also helped, @pkosenko. So it should all work as expected now.

**Comment by pkosenko** [comment]
I put Keystone on the shelf for a while working on other things.  After updating the keystone-generator, I was able to create a new installation using SASS.  So the problem indeed seems to fixed.

**Comment by JedWatson** [comment]
Good to hear, thanks for confirming!

**Comment by pkosenko** [comment]
@jamlen

Oh, no . . . FYI . . . I was getting a raft of errors of all sorts until I figured I had better UPDATE the generator.  After doing that, the error disappeared, although I was still getting node warnings due to my newer Node.  Since I had the error I have updated NODE itself to 0.12.2.   But try updating the generator.

**Comment by trickycdm** [comment]
I had a problem trying to use sass as well, had to bin the project and restart with less.

**Comment by morenoh149** [comment]
@trickycdm what version of node are you running? Don't bin help us fix the generators.

**Comment by pkosenko** [comment]
I had the problem back in May and I haven't actually been using Keystone again since then.  I believe that I was at Node 0.12.0 back then and I am now up to Node 0.12.2.  In other words, I am not jumping to update until I need to do so.  Newest node is already up to 4.2.  So I am probably not going to be of very much help with your problem, because out-of-date (until I get back to it).

**Comment by TheRoadSouth** [comment]
Ran into this same error when playing around with the master branch (v0.4). 

When following these instructions:
https://github.com/keystonejs/keystone/blob/master/README.md#linking-keystone-for-development-and-testing

You'll also need to run the following command in your local 0.4 keystone folder:
npm install node-sass-middleware --save

**Comment by morenoh149** [comment]
I'm pretty sure this issue is resolved. Typical users will use the latest generator, which specifies the correct node-sass-middleware if they choose sass. And beta testers know to search for these problems to find issues like this thread.
